name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome and thank you for this issue. Please note that this repo is moving to knative-sandbox'
        pr-message: 'Welcome and thank you for this PR. Please note that this repo is moving to knative-sandbox'
